name: chubbyphp-petstore
services:
  php:
    container_name: chubbyphp-petstore-php
    hostname: chubbyphp-petstore-php
    build:
      dockerfile: ./docker/development/php/Dockerfile
      context: ./
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    userns_mode: keep-id
    environment:
      APP_ENV: dev
      MONGO_URI: mongodb://petstore:4aAUfBjDACcdZxNwJgJ6@mongo:27017
      SSH_AUTH_SOCK: /ssh-agent
    volumes:
      - ${PWD}:/app
      - $SSH_AUTH_SOCK:/ssh-agent
      # bash
      - ~/.bash_docker:/home/php/.bash_docker
      - ~/.bash_history:/home/php/.bash_history
      # zsh
      - ~/.zsh_docker:/home/php/.zsh_docker
      - ~/.zsh_history:/home/php/.zsh_history
      # git
      - ~/.gitconfig:/home/php/.gitconfig
      - ~/.gitignore:/home/php/.gitignore
      # opencode - coding agent
      - ~/.config/opencode/tui.json:/home/php/.config/opencode/tui.json
      - ~/.local/share/opencode/auth.json:/home/php/.local/share/opencode/auth.json
      # pi
      - ~/.pi/agent/auth.json:/home/php/.pi/agent/auth.json
    depends_on:
      - mongo
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '9003:9003'
  php-fluentd:
    container_name: chubbyphp-petstore-php-fluentd
    hostname: chubbyphp-petstore-php-fluentd
    build:
      dockerfile: ./docker/production/php-fluentd/Dockerfile
      context: ./
    user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
    environment:
      STACK: 'local'
      OPENSEARCH_HOSTS: 'opensearch:9200'
      OPENSEARCH_USER: 'admin'
      OPENSEARCH_PASSWORD: '98T722Eqw99oqFCSJCnB'
      OPENSEARCH_SSL_VERIFY: 'false'
    volumes:
      - ${PWD}/var/log:/app/var/log
    depends_on:
      - opensearch
  mongo:
    container_name: chubbyphp-petstore-mongo
    hostname: chubbyphp-petstore-mongo
    image: mongo:8.0.4 # check before upgrade https://www.mongodb.com/community/forums/t/mongodb-8-x-and-linux-kernel-6-19/337547
    environment:
      MONGO_INITDB_ROOT_USERNAME: petstore
      MONGO_INITDB_ROOT_PASSWORD: 4aAUfBjDACcdZxNwJgJ6
    ports:
      - '27017:27017'
    volumes:
      - mongo:/data/db
  nginx:
    container_name: chubbyphp-petstore-nginx
    hostname: chubbyphp-petstore-nginx
    image: nginx:1
    environment:
      SERVER_PORT: '443'
      PHP_FPM_SERVER_HOST: 'php'
      PHP_FPM_SERVER_PORT: '9000'
      SWAGGER_SERVER_HOST: 'swagger-ui'
      SWAGGER_SERVER_PORT: '8080'
    ports:
      - '443:443'
    volumes:
      - ./docker/development/nginx:/etc/nginx/templates
      - ${PWD}/public:/app/public:ro
    depends_on:
      - php
      - swagger-ui
  opensearch:
    container_name: chubbyphp-petstore-opensearch
    hostname: chubbyphp-petstore-opensearch
    image: opensearchproject/opensearch:2
    environment:
      ES_JAVA_OPTS: '-Xms512m -Xmx512m'
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: '98T722Eqw99oqFCSJCnB'
      discovery.type: 'single-node'
    ports:
      - 9200:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'curl -sk https://localhost:9200 | grep -q "Unauthorized"'
        ]
      interval: 10s
      timeout: 10s
      retries: 120
  opensearch-dashboard:
    container_name: chubbyphp-petstore-opensearch-dashboard
    hostname: chubbyphp-petstore-opensearch-dashboard
    image: opensearchproject/opensearch-dashboards:2
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch:9200"]'
    ports:
      - 5601:5601
  swagger-ui:
    container_name: chubbyphp-petstore-swagger-ui
    hostname: chubbyphp-petstore-swagger-ui
    image: swaggerapi/swagger-ui
    environment:
      BASE_URL: /swagger
      URLS: '[ { url: "/openapi" } ]'
volumes:
  mongo:
