version: '3.0'
services:
  php:
    container_name: petstore-php
    hostname: petstore-php
    build:
      dockerfile: ./docker/development/php/Dockerfile
      context: ./
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    environment:
      APP_ENV: dev
      DATABASE_USER: root
      DATABASE_PASS: 4aAUfBjDACcdZxNwJgJ6
      DATABASE_HOST: postgres
      DATABASE_NAME: petstore
      DATABASE_PORT: 5432
      SSH_AUTH_SOCK: /ssh-agent
    volumes:
      - ${PWD}:/app
      - ~/.bash_docker:/home/php/.bash_docker
      - ~/.bash_history:/home/php/.bash_history
      - ~/.gitconfig:/home/php/.gitconfig
      - ~/.gitignore:/home/php/.gitignore
      - ~/.zsh_docker:/home/php/.zsh_docker
      - ~/.zsh_history:/home/php/.zsh_history
      - $SSH_AUTH_SOCK:/ssh-agent
    depends_on:
      - postgres
    extra_hosts:
      - "host.docker.internal:host-gateway"
  postgres:
    container_name: petstore-postgres
    hostname: petstore-postgres
    image: postgres:14
    command: -c log_statement=all -c log_error_verbosity=VERBOSE
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 4aAUfBjDACcdZxNwJgJ6
    ports:
      - '5432:5432'
    volumes:
      - ./database/postgres:/var/lib/postgresql/data
  nginx:
    container_name: petstore-nginx
    hostname: petstore-nginx
    build:
      dockerfile: ./docker/development/nginx/Dockerfile
      context: ./
    ports:
      - '443:443'
    volumes:
      - ${PWD}:/app:ro
    depends_on:
      - php
