version: '3.0'
services:
  php:
    container_name: petstore-php
    hostname: petstore-php
    build:
      dockerfile: ./docker/development/php/Dockerfile
      context: ./
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    environment:
      APP_ENV: dev
      DATABASE_USER: root
      DATABASE_PASS: 4aAUfBjDACcdZxNwJgJ6
      DATABASE_HOST: postgres
      DATABASE_NAME: petstore
      DATABASE_PORT: 5432
      SSH_AUTH_SOCK: /ssh-agent
    volumes:
      - ${PWD}:/app
      - ~/.bash_docker:/home/php/.bash_docker
      - ~/.bash_history:/home/php/.bash_history
      - ~/.gitconfig:/home/php/.gitconfig
      - ~/.gitignore:/home/php/.gitignore
      - ~/.zsh_docker:/home/php/.zsh_docker
      - ~/.zsh_history:/home/php/.zsh_history
      - $SSH_AUTH_SOCK:/ssh-agent
    depends_on:
      - postgres
    extra_hosts:
      - "host.docker.internal:host-gateway"
  postgres:
    container_name: petstore-postgres
    hostname: petstore-postgres
    image: postgres:14
    command: -c log_statement=all -c log_error_verbosity=VERBOSE
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 4aAUfBjDACcdZxNwJgJ6
    ports:
      - '5432:5432'
    volumes:
      - ./database/postgres:/var/lib/postgresql/data
  swagger-ui:
    container_name: petstore-swagger-ui
    hostname: petstore-swagger-ui
    image: swaggerapi/swagger-ui
    environment:
      BASE_URL: /swagger
      URLS: '[ { url: "/openapi" } ]'
  nginx:
    container_name: petstore-nginx
    hostname: petstore-nginx
    image: nginx
    environment:
      SERVER_PORT: '443'
      PHP_FPM_SERVER_HOST: 'php'
      PHP_FPM_SERVER_PORT: '9000'
      SWAGGER_SERVER_HOST: 'swagger-ui'
      SWAGGER_SERVER_PORT: '8080'
    ports:
      - '443:443'
    volumes:
      - ./docker/development/nginx:/etc/nginx/templates
      - ${PWD}/public:/app/public:ro
    depends_on:
      - php
      - swagger-ui
